### ISSUE TITLE
Rewrite all /opt/app-root to $APP_ROOT variable

### ISSUE THREAD

**Issue by michal-josef-spacek** [sclorg/s2i-perl-container#241]
s2i image has $APP_ROOT environment variable, but in code there are many hardcoded variables

**Comment by phracek** [comment]
This is already fixed by #236

**Comment by michal-josef-spacek** [comment]
@phracek I don't think that is ok or that's working.

e.g.
https://github.com/sclorg/s2i-perl-container/blob/master/5.32/s2i/bin/assemble#L15
https://github.com/sclorg/s2i-perl-container/blob/master/5.32/s2i/bin/assemble#L101
Multiple hardcoded in https://github.com/sclorg/s2i-perl-container/blob/master/5.32/s2i/bin/run
Same https://github.com/sclorg/s2i-perl-container/blob/master/5.32/Dockerfile.fedora#L11

And most funny part:
https://github.com/sclorg/s2i-perl-container/blob/master/5.32/Dockerfile.fedora#L47
```
# Copy extra files to the image.
COPY ./root/ /
```
Which copies ./root/opt/app-root directly to /

**Comment by zmiklank** [comment]
I will take a look at this.

**Comment by zmiklank** [comment]
Seems there already is some initiative about this: https://github.com/sclorg/s2i-perl-container/pull/288

**Comment by michal-josef-spacek** [comment]
We need to test and rewrite other Perl versions.

**Comment by phracek** [comment]
@michal-josef-spacek It looks like this issue is already fixed by #288. Can we close it?

**Comment by michal-josef-spacek** [comment]
@phracek There are places, which need to rewrite still

**Comment by zmiklank** [comment]
@phracek @michal-josef-spacek I volunteered to do this, but I put so low priority on it that it is still not finished. I may reprioritize it a bit.
